version: '3.1'
services:
  notes-db:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: 'databasenotas'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db:/var/lib/mysql
  #notes-backend:
    #build: Notes-App/Fullstack-Notes/BackendNotas/Docker
    #ports:
      #- "8080:8080"
    #depends_on:
      #- notes-db
volumes:
  db:
